[workspace]
members = [
    "qsniffer",
    "qexed_packet_macros",
    "qexed_tcp_connect",
]
resolver = "3"
[workspace.dependencies]
qexed_packet_macros={version = "*",path="qexed_packet_macros"}
qexed_tcp_connect ={version = "*",path="qexed_tcp_connect"}