[workspace]
members = [
    "qsniffer",
    "qexed_packet_macros",
    "qexed_tcp_connect",
]
resolver = "3"
[workspace.dependencies]
qexed_packet_macros={version = "0.1.0",path="qexed_packet_macros"}
qexed_tcp_connect ={version = "0.1.0",path="qexed_tcp_connect"}