[package]
name = "qexed_packet_macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "一个数据包定义工具" # 补充元数据消除警告
exclude = [
    "target/",           # 排除整个编译目录
    "Cargo.lock",        # 对于库项目，通常排除锁文件
    "*.log",             # 排除日志文件
    "**/*.bk",           # 排除备份文件
]
[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"